version: "3.9"

services:

  ecomm:
    image: kauamax/ecomm:1.0
    container_name: ecomm
    environment:
      - DB_PORT=$DB_PORT
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
    depends_on:
      - mongo-ecomm

  mongo-ecomm:
    image: mongo
    container_name: mongo-ecomm
    restart: always
    ports:
      - $DB_PORT:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    volumes:
      - db-mongo-ecomm:/data/db
      - type: bind
        source: ./mongo
        target: /mongo-scripts

volumes:
  db-mongo-ecomm:
    driver: local